export const VENEZUELA_LOCATIONS = {
  Amazonas: [
    'Puerto Ayacucho',
    'La Esmeralda',
    'Maroa',
    'San Carlos de Río Negro',
    'San Fernando de Atabapo',
  ],
  Anzoátegui: [
    'Anaco',
    'Aragua de Barcelona',
    'Barcelona',
    'Cantaura',
    'Clarines',
    'El Tigre',
    'Lechería',
    'Pariaguán',
    'Puerto La Cruz',
    'Puerto Píritu',
  ],
  Apure: ['Achaguas', 'Biruaca', 'Elorza', 'Guasdualito', 'Mantecal', 'San Fernando de Apure'],
  Aragua: [
    'Cagua',
    'El Limón',
    'La Victoria',
    'Maracay',
    'Ocumare de la Costa',
    'Palo Negro',
    'San Mateo',
    'Turmero',
    'Villa de Cura',
  ],
  Barinas: ['Barinas', 'Barinitas', 'Ciudad Bolivia', 'Libertad', 'Sabaneta', 'Santa Bárbara de Barinas', 'Socopó'],
  Bolívar: [
    'Caicara del Orinoco',
    'Ciudad Bolívar',
    'Ciudad Guayana',
    'El Callao',
    'Guasipati',
    'Santa Elena de Uairén',
    'Tumeremo',
    'Upata',
  ],
  Carabobo: ['Bejuma', 'Guacara', 'Mariara', 'Morón', 'Naguanagua', 'Puerto Cabello', 'San Joaquín', 'Tocuyito', 'Valencia'],
  Cojedes: ['El Baúl', 'Las Vegas', 'San Carlos', 'Tinaco', 'Tinaquillo'],
  'Delta Amacuro': ['Curiapo', 'Pedernales', 'Sierra Imataca', 'Tucupita'],
  'Distrito Capital': ['Caracas'],
  Falcón: ['Chichiriviche', 'Churuguara', 'Coro', 'Dabajuro', 'La Vela de Coro', 'Punto Fijo', 'Tucacas'],
  Guárico: [
    'Altagracia de Orituco',
    'Calabozo',
    'El Sombrero',
    'Las Mercedes del Llano',
    'San Juan de los Morros',
    'Tucupido',
    'Valle de la Pascua',
    'Zaraza',
  ],
  'La Guaira': ['Caraballeda', 'Carayaca', 'Catia La Mar', 'La Guaira', 'Macuto', 'Maiquetía', 'Naiguatá'],
  Lara: ['Barquisimeto', 'Cabudare', 'Carora', 'Duaca', 'El Tocuyo', 'Quíbor', 'Sanare', 'Sarare', 'Siquisique'],
  Mérida: ['Bailadores', 'Ejido', 'El Vigía', 'Lagunillas', 'Mérida', 'Mucuchíes', 'Santa Cruz de Mora', 'Tovar'],
  Miranda: [
    'Baruta',
    'Chacao',
    'Charallave',
    'Cúa',
    'Guarenas',
    'Guatire',
    'Higuerote',
    'Los Teques',
    'Ocumare del Tuy',
    'Petare',
    'Río Chico',
    'Santa Teresa del Tuy',
  ],
  Monagas: ['Barrancas del Orinoco', 'Caicara de Maturín', 'Caripe', 'Caripito', 'Maturín', 'Punta de Mata', 'Temblador'],
  'Nueva Esparta': ['Boca del Río', 'El Valle del Espíritu Santo', 'Juan Griego', 'La Asunción', 'Pampatar', 'Porlamar'],
  Portuguesa: ['Acarigua', 'Araure', 'Biscucuy', 'Guanare', 'Ospino', 'Píritu', 'Turén', 'Villa Bruzual'],
  Sucre: ['Araya', 'Cariaco', 'Carúpano', 'Cumaná', 'Cumanacoa', 'Güiria', 'Irapa', 'Río Caribe'],
  Táchira: [
    'Capacho',
    'Colón',
    'La Fría',
    'La Grita',
    'Palmira',
    'Rubio',
    'San Antonio del Táchira',
    'San Cristóbal',
    'Táriba',
    'Ureña',
  ],
  Trujillo: ['Betijoque', 'Boconó', 'Carache', 'Escuque', 'La Puerta', 'Pampán', 'Sabana de Mendoza', 'Trujillo', 'Valera'],
  Yaracuy: ['Aroa', 'Chivacoa', 'Cocorote', 'Nirgua', 'San Felipe', 'Urachiche', 'Yaritagua'],
  Zulia: [
    'Cabimas',
    'Ciudad Ojeda',
    'Encontrados',
    'La Concepción',
    'Lagunillas',
    'Machiques',
    'Maracaibo',
    'Mene Grande',
    'San Carlos del Zulia',
    'Santa Bárbara del Zulia',
    'Villa del Rosario',
  ],
} as const;

export type VenezuelaState = keyof typeof VENEZUELA_LOCATIONS;

export const VENEZUELA_STATES = Object.keys(VENEZUELA_LOCATIONS) as VenezuelaState[];

export const getCitiesByState = (state?: string): readonly string[] => {
  if (!state || !(state in VENEZUELA_LOCATIONS)) return [];
  return VENEZUELA_LOCATIONS[state as VenezuelaState];
};
